name: "build"

'on':
  push:
    branches: "**"
    tags-ignore: ["**"]
  pull_request:

concurrency:
  group: "${{ github.workflow }}-${{ github.event.number || github.ref }}"
  cancel-in-progress: true

jobs:
  build:
    # Only run on PRs if the source branch is on someone else's repo
    if: "${{ github.event_name != 'pull_request' || github.repository != github.event.pull_request.head.repo.full_name }}"
    strategy:
      matrix:
        os: ["ubuntu-latest"]
        # os: ["ubuntu-latest", "windows-latest"]
    runs-on: "${{ matrix.os }}"
    steps:
      - name: "checkout repository"
        uses: "actions/checkout@v4"
      - name: "setup jdk 11"
        uses: "actions/setup-java@v4"
        with:
          distribution: "temurin"
          java-version: "11"
      - name: "Run Gradle build"
        id: "gradle-build"
        uses: "./.github/actions/run-gradle-capturing"
        with:
          store-cache: "${{ github.ref != 'refs/heads/trunk' || github.event_name == 'pull_request' }}"
          arguments: build
      - name: Determine status
        if: "${{ runner.os == 'Linux' }}"
        run: |
          if [ "$(echo '${{ steps.gradle-build.outputs.version }}' | grep '\-SNAPSHOT')" ]; then
            echo "STATUS=snapshot" >> $GITHUB_ENV
          else
            echo "STATUS=release" >> $GITHUB_ENV
          fi
      - name: "publish"
        if: "${{ runner.os == 'Linux' && env.STATUS != 'release' && github.event_name == 'push' && github.ref == 'refs/heads/trunk' }}"
        uses: "gradle/gradle-build-action@v3"
        with:
          arguments: publish
        env:
          ORG_GRADLE_PROJECT_stellardriftUsername: "${{ secrets.STELLARDRIFT_USERNAME }}"
          ORG_GRADLE_PROJECT_stellardriftPassword: "${{ secrets.STELLARDRIFT_PASSWORD }}"
